package consumer

import "modulus/kyc/common"

// The mapping from the common gender values to the API-acceptable values.
var gender2API = map[common.Gender]string{
	common.Male:   "M",
	common.Female: "F",
}

var resultCodes = map[int]string{
	100:   "Good User Account Info",
	101:   "Unknown User Account Info",
	102:   "Bad User Account Info",
	103:   "Suspicious User Account Info",
	104:   "Very Good User Account Info",
	110:   "Good Device",
	111:   "Unknown Device",
	112:   "Bad Device",
	113:   "Suspicious Device",
	114:   "Very Good Device",
	120:   "Known Payment Instrument",
	121:   "Unknown Payment Instrument",
	122:   "Bad Payment Instrument",
	123:   "Suspicious Payment Instrument",
	124:   "Very Good Payment Instrument",
	130:   "Trusted User",
	131:   "Unknown User",
	132:   "Bad User",
	133:   "Recognized User",
	134:   "Suspicious User",
	150:   "No Relationship",
	151:   "User Account Info, Device and Payment Instrument all related",
	152:   "User Account Info and Device related",
	153:   "User Account Info and Payment Instrument related",
	154:   "Device and Payment Instrument related",
	155:   "Payment Instrument related to User Account Info and Device via a household relationship",
	156:   "User Account Info related to Payment Instrument and Device via a household relationship",
	157:   "Device related to User Account Info and Payment Instrument via a household relationship",
	158:   "User Account Info related to Payment Instrument, and Payment Instrument related to device",
	159:   "User Account Info related to device, and User Account Info related to Payment Instrument",
	160:   "User Account Info related to device, and device related to Payment Instrument",
	180:   "Trusted Shipping Address",
	181:   "Unknown Shipping Address",
	182:   "Bad Shipping Address",
	183:   "Recognized Shipping Address",
	184:   "Suspicious Shipping Address",
	190:   "Automated Review Policy Disabled",
	191:   "Automated Review Policy Rejected",
	192:   "Automated Review Policy Accepted",
	193:   "Automated Review Policy Transaction Filtered",
	194:   "Automated Review Policy Indeterminate",
	195:   "Automated Review Policy Pending",
	200:   "Validated User",
	201:   "User Who Has Failed Validation",
	202:   "Un-validated User",
	210:   "Good Destination User Account Info",
	211:   "Unknown Destination User Account Info",
	212:   "Bad Destination User Account Info",
	213:   "Suspicious Destination User Account Info",
	214:   "Very Good Destination User Account Info",
	220:   "Known Destination Payment Instrument",
	221:   "Unknown Destination Payment Instrument",
	222:   "Bad Destination Payment Instrument",
	223:   "Suspicious Destination Payment Instrument",
	224:   "Very Good Destination Payment Instrument",
	501:   "Fraudulent Device",
	502:   "Fraudulent Payment",
	503:   "Fraudulent User Account",
	504:   "Suspicious Device",
	505:   "Suspicious Payment",
	506:   "Suspicious User Account",
	507:   "Validated User",
	508:   "User who previously failed validation",
	509:   "Existing Trusted User",
	510:   "Existing, but newly created User",
	511:   "New User, with good existing User Account, Device and Payment",
	512:   "New User, with entities related via household relationships",
	516:   "New account information, but previously used shipping address by the payment/device",
	517:   "New account information, and a new shipping address",
	518:   "New account information, for a device and payment pair",
	519:   "New payment, but same billing address as other payments used by account/device",
	520:   "New payment with new billing address for this account/device",
	521:   "New payment for a device and user account pair",
	522:   "New device with the same IP as a previously used device",
	523:   "New device with a new IP, but using an existing shipping address for account/payment",
	524:   "New device with a new IP and using a new shipping address",
	525:   "New device with a new IP and no shipping address supplied",
	526:   "New device for a payment and user account pair",
	528:   "Previously unrelated good payment and device, no user account information supplied",
	529:   "Existing relationship between payment and user account, no device information supplied, but using an existing shipping address",
	530:   "Good Payment, neither device nor user account information supplied",
	531:   "First Time Access",
	532:   "Infrequent Access, over a long period of time",
	533:   "Infrequent Access, over a short time period",
	534:   "New device and payment, no user account information supplied",
	535:   "New payment and user account info, no device information supplied",
	536:   "New payment, neither device nor user account information supplied",
	537:   "Good device and a new payment, no user account information supplied",
	538:   "Good payment and a new device, no user account information supplied",
	539:   "Good user account information and a new payment, no device information supplied",
	540:   "Good payment and new user account information, no device information supplied",
	541:   "Existing payment and device, though recently created, no user account information supplied",
	542:   "Existing payment and device, no user account information supplied",
	543:   "Existing relationship between payment and user account, no device information supplied",
	544:   "Recently created existing relationship between payment and user account, no device information supplied",
	545:   "Good Payment and User Account information, previously unrelated, no device information supplied",
	546:   "Existing relationship between good User Account information and neutral device and payment",
	547:   "Recently created existing relationship between good User Account information, and neutral device and payment",
	548:   "Good User Account information with a new payment and device",
	549:   "Existing relationship between a good payment and neutral device and user account information",
	550:   "Recently created existing relationship between a good payment and neutral device and user account information",
	551:   "Good payment with new device and user account information",
	552:   "Existing relationship between a good device and neutral payment and user account information",
	553:   "Recently created existing relationship between a good device and neutral payment and user account information",
	554:   "Good device with new payment and user account information",
	555:   "Validated User, that has been recently created",
	556:   "New account information, no shipping address provided",
	557:   "User validation extended to user with new device",
	558:   "User validation extended to user with new device",
	559:   "User validation extended to user with new payment",
	560:   "User validation extended to user with new payment",
	561:   "User validation extended to user with new account info",
	562:   "User validation extended to user with new account info",
	563:   "Validated user using a new device and a new shipping address",
	564:   "Validated user using a new device and a new shipping address",
	565:   "Good Payment Instrument, neither device nor user account information supplied",
	566:   "Good Payment Instrument with clean history, neither device nor user account information supplied",
	567:   "Fraudulent Shipping Address",
	568:   "Suspicious Shipping Address",
	599:   "Error",
	50001: "User is Validated (Account Transaction)",
	50002: "User failed validation (Account Transaction)",
	50003: "Bad User (Account Transaction)",
	50004: "Trusted User (Account Transaction)",
	50005: "Unknown User (Account Transaction)",
	50006: "New Device for Validated User (Account Transaction)",
	50007: "New Payment for Validated User (Account Transaction)",
	50008: "New Account for Validated User (Account Transaction)",
	50009: "Validation Extended for Account",
	50010: "Good History of Account and Destination Payment",
	50011: "Recent History of Account and Destination Payment",
}
