package model

// List of AssociateType values.
const (
	Advisor                         AssociateType = "ADVISOR"
	AgentRepresentative             AssociateType = "AGENT_REPRESENTATIVE"
	AffiliatedCompany               AssociateType = "AFFILIATED_COMPANY"
	AffiliatedOrganization          AssociateType = "AFFILIATED_ORGANIZATION"
	AffiliatedPosition              AssociateType = "AFFILIATED_POSITION"
	Asset                           AssociateType = "ASSET"
	Assistant                       AssociateType = "ASSISTANT"
	AssociateAT                     AssociateType = "ASSOCIATE"
	AssociatedSpecialInterestPerson AssociateType = "ASSOCIATED_SPECIAL_INTEREST_PERSON"
	Aunt                            AssociateType = "AUNT"
	Banker                          AssociateType = "BANKER"
	BranchOffice                    AssociateType = "BRANCH_OFFICE"
	Brother                         AssociateType = "BROTHER"
	BrotherInLaw                    AssociateType = "BROTHER_IN_LAW"
	BusinessAssociate               AssociateType = "BUSINESS_ASSOCIATE"
	Child                           AssociateType = "CHILD"
	Client                          AssociateType = "CLIENT"
	Colleague                       AssociateType = "COLLEAGUE"
	Cousin                          AssociateType = "COUSIN"
	CoDefendant                     AssociateType = "CO_DEFENDANT"
	Daughter                        AssociateType = "DAUGHTER"
	DaughterInLaw                   AssociateType = "DAUGHTER_IN_LAW"
	Director                        AssociateType = "DIRECTOR"
	DocCompany                      AssociateType = "DOC_COMPANY"
	Employee                        AssociateType = "EMPLOYEE"
	Employer                        AssociateType = "EMPLOYER"
	Executive                       AssociateType = "EXECUTIVE"
	ExHusband                       AssociateType = "EX_HUSBAND"
	ExWife                          AssociateType = "EX_WIFE"
	Family                          AssociateType = "FAMILY"
	FamilyMember                    AssociateType = "FAMILY_MEMBER"
	Father                          AssociateType = "FATHER"
	FatherInLaw                     AssociateType = "FATHER_IN_LAW"
	FinancialAdvisor                AssociateType = "FINANCIAL_ADVISOR"
	Friend                          AssociateType = "FRIEND"
	FrontCompany                    AssociateType = "FRONT_COMPANY"
	GrandDaughter                   AssociateType = "GRANDDAUGHTER"
	GrandFather                     AssociateType = "GRANDFATHER"
	GrandMother                     AssociateType = "GRANDMOTHER"
	GrandSon                        AssociateType = "GRANDSON"
	GrandChild                      AssociateType = "GRAND_CHILD"
	GroupBeneficialOwner            AssociateType = "GROUP_BENEFICIAL_OWNER"
	Husband                         AssociateType = "HUSBAND"
	KeyMember                       AssociateType = "KEY_MEMBER"
	LegalAdvisor                    AssociateType = "LEGAL_ADVISOR"
	Misc                            AssociateType = "MISC"
	Mother                          AssociateType = "MOTHER"
	MotherInLaw                     AssociateType = "MOTHER_IN_LAW"
	Nephew                          AssociateType = "NEPHEW"
	Niece                           AssociateType = "NIECE"
	Nominee                         AssociateType = "NOMINEE"
	Operator                        AssociateType = "OPERATOR"
	Owner                           AssociateType = "OWNER"
	Parent                          AssociateType = "PARENT"
	PoliticalAdvisor                AssociateType = "POLITICAL_ADVISOR"
	RegisteredOwner                 AssociateType = "REGISTERED_OWNER"
	Relative                        AssociateType = "RELATIVE"
	SameSexSpouse                   AssociateType = "SAME_SEX_SPOUSE"
	SeniorOfficial                  AssociateType = "SENIOR_OFFICIAL"
	ShareholderOwner                AssociateType = "SHAREHOLDER_OWNER"
	ShipManager                     AssociateType = "SHIP_MANAGER"
	Sister                          AssociateType = "SISTER"
	SisterInLaw                     AssociateType = "SISTER_IN_LAW"
	Son                             AssociateType = "SON"
	SonInLaw                        AssociateType = "SON_IN_LAW"
	Spouse                          AssociateType = "SPOUSE"
	StepDaughter                    AssociateType = "STEP_DAUGHTER"
	StepSon                         AssociateType = "STEP_SON"
	StepFather                      AssociateType = "STEPFATHER"
	StepMother                      AssociateType = "STEPMOTHER"
	Subsidiary                      AssociateType = "SUBSIDIARY"
	TechnicalManager                AssociateType = "TECHNICAL_MANAGER"
	Uncle                           AssociateType = "UNCLE"
	UnknownAT                       AssociateType = "UNKNOWN"
	UnmarriedPartner                AssociateType = "UNMARRIED_PARTNER"
	Wife                            AssociateType = "WIFE"
)

// Associate represents an associate.
type Associate struct {
	Type                   AssociateType `json:"type"`
	Reversed               bool          `json:"reversed"`
	TargetEntityID         string        `json:"targetEntityId"`
	TargetExternalImportID string        `json:"targetExternalImportId"`
}

// AssociateType represents the associate type enumeration.
type AssociateType string
